language = 'uz'
name = 'Uzbek'

variants.default.display = 'default'

[[mappings]]

'А' = 'A'                                               #  1
'а' = 'a'
'Б' = 'B'                                               #  2
'б' = 'b'
'В' = 'V'                                               #  3
'в' = 'v'
'Г' = 'G'                                               #  4
'г' = "g"
'Ғ' = [["G'", "G`"]]                                    #  5
'ғ' = ["g'", "g`"]
'Д' = "D"                                               #  6
'д' = "d"
'Е' = "E"                                               #  7
'е' = "e"
'Ё' = [["Yo", "YO"]]                                    #  8
'ё' = "yo"

[[mappings]]

'Ж' = "J"                                               #  9
'ж' = "j"
'З' = "Z"                                               # 10
'з' = "z"
'И' = "I"                                               # 11
'и' = "i"
'Й' = "Y"                                               # 12
'й' = "y"
'К' = "K"                                               # 13
'к' = "k"
'Қ' = "Q"                                               # 14
'қ' = "q"
'Л' = "L"                                               # 15
'л' = "l"
'М' = "M"                                               # 16
'м' = "m"

[[mappings]]

'Н' = "N"                                               # 17
'н' = "n"
'О' = "O"                                               # 18
'о' = "o"
'П' = "P"                                               # 19
'п' = "p"
'Р' = "R"                                               # 20
'р' = "r"
'С' = "S"                                               # 21
'с' = "s"
'Т' = "T"                                               # 22
'т' = "t"
'У' = "U"                                               # 23
'у' = "u"
'Ў' = ["O'", "O`"]                                      # 24
'ў' = ["o'", "o`"]

[[mappings]]

'Ф' = "F"                                               # 25
'ф' = "f"
'Х' = "X"                                               # 26
'х' = "x"
'Ҳ' = "H"                                               # 27
'ҳ' = "h"
'Ц' = [["Ts", "TS"]]                                    # 28
'ц' = "ts"
'Ч' = [["Ch", "CH"]]                                    # 29
'ч' = "ch"
'Ш' = [["Sh", "SH"]]                                    # 30
'ш' = "sh"
'Ъ' = "'"                                               # 31
'ъ' = "'"
'Э' = [["Ee", "EE"]]                                    # 32
'э' = "ee"
'Ю' = [["Yu", "YU"]]                                    # 33
'ю' = "yu"
'Я' = [["Ya", "YA"]]                                    # 34
'я' = "ya"

[footer]

content = """
❗️To enter combinations such as <code>сх</code> press <code>ESC</code>
after the first letter to stop recognition. That is <code>s\u00A0ESC\u00A0h</code> will
produce <code>сх</code>.
"""
